"""Probability maps and ROIs must match what the original TensorFlow implementation produced.

``tests/fixtures/e2e_reference.npz`` was generated by running the unchanged original code
(``make_e2e_reference.py``) on a synthetic movie with the shipped DeXNets.
"""

from pathlib import Path

import numpy as np
import pytest

from dextrusion.inference import detect
from dextrusion.postprocess import cleaned_probamap, get_events

ROOT = Path(__file__).parent.parent
REF = np.load(ROOT / "tests" / "fixtures" / "e2e_reference.npz")
NETS = ROOT / "models" / "notum_all"
ALL0, ALL1 = NETS / "notumAll0", NETS / "notumAll1"

CASES = {
    "single": ([ALL0], {}),
    "ensemble": ([ALL0, ALL1], {}),
    "rescaled": ([ALL0], {"cell_diameter": 40, "extrusion_duration": 9}),
}


def as_sorted(events):
    return sorted((e.t, e.y, e.x) for e in events)


@pytest.mark.parametrize("name", CASES)
def test_probability_maps_match_original(name):
    models, kwargs = CASES[name]
    res = detect(REF["movie"], models, dxy=25, dz=2, group_size=1000, device="cpu", **kwargs)
    ref = REF[f"{name}_raw"]
    assert res.probamap.shape == ref.shape
    diff = np.abs(res.probamap.astype(int) - ref.astype(int))
    # float32 softmax differences can flip the last uint8 level of a few pixels, no more
    assert diff.max() <= 1
    assert (diff > 0).mean() < 0.01
    for cat in range(1, 4):
        got = as_sorted(get_events(res.probamap[cat - 1], REF["movie"].shape, 50, 100, 10, 4))
        assert got == sorted(map(tuple, REF[f"{name}_rois_{cat}"].tolist()))


@pytest.mark.parametrize("tag,vol,proba", [("", 800, 180), ("loose_", 0, 0), ("mid_", 150, 120)])
def test_postprocessing_matches_original(tag, vol, proba):
    probamap = REF["post_probamap"]
    for cat in range(1, 4):
        got = as_sorted(get_events(probamap[cat - 1], (80, 192, 192), vol, proba, 10, 4))
        assert got == sorted(map(tuple, REF[f"post_{tag}rois_{cat}"].tolist()))


def test_cleaned_probamap_matches_original():
    got = cleaned_probamap(REF["post_probamap"][0], 150, 120, 10, 4)
    np.testing.assert_array_equal(got, REF["post_clean_1"])


# ---- event-level scoring: original RoiUtils vs evaluate.py -----------------------------
@pytest.mark.parametrize("i", range(14))
@pytest.mark.parametrize("dxy,dt", [(15, 4), (10, 3)])
def test_event_scoring_matches_original(i, dxy, dt):
    from dextrusion.evaluate import compare, false_negatives, false_positives

    det = [tuple(r) for r in REF[f"score_{i}_det"].tolist()]
    gt = [tuple(r) for r in REF[f"score_{i}_gt"].tolist()]
    tp, fp, fn, precision, recall = REF[f"score_{i}_{dxy}_{dt}"]
    s = compare(det, gt, dxy, dt)
    assert (s.tp, s.fp, s.fn) == (tp, fp, fn)
    assert s.precision == pytest.approx(precision, abs=1e-12)
    assert s.recall == pytest.approx(recall, abs=1e-12)
    assert false_positives(det, gt, dxy, dt) == [tuple(r) for r in REF[f"score_{i}_{dxy}_{dt}_fp"].tolist()]
    assert false_negatives(det, gt, dxy, dt) == [tuple(r) for r in REF[f"score_{i}_{dxy}_{dt}_fn"].tolist()]
